rtmp:
  port: 1935
  host: 0.0.0.0

streams:
  - app: norsk
    stream: ch01
    host: ashton-nuc
    port: 11931
  - app: norsk
    stream: ch02
    host: ashton-nuc
    port: 11932
  - app: norsk
    stream: ch03
    host: ashton-nuc
    port: 11933
