rtmp:
  port: 1935
  host: 0.0.0.0

streams:
  - from:
      app: norsk
      stream: ch01
    to:
      app: norsk
      stream: stream
      host: ashton-nuc
      port: 11931
  - from:
      app: norsk
      stream: ch02
    to:
      app: norsk
      stream: stream
      host: ashton-nuc
      port: 11932
  - from:
      app: norsk
      stream: ch03
    to:
      app: norsk
      stream: stream
      host: ashton-nuc
      port: 11933
